language: c
addons:
  apt:
    update: true
    packages:
      - make
      - gcc
      - build-essential
      - libc6-dev
      - libgcc1
      - wget
      - bzip2
  sonarcloud:
    organization: "h2lab"
    token:
      secure: "DB6hStf7iewNO20/Owe4RvtwVmavCj9q1mh/x3yGfCqZiXeJnap9CxqLZG3pQo9GBfgAZ/wIukbKrYn+oW7hv4vTTJFRKbxXpSIKSiUJX51MN3EcSZyqQ4RwQnR2ufGK09afZ2GoRtU/SXrMks8okEg2fMMcVu3uJRrzu6Tx5FzOTQHO4b6o8R7ZA8VSRJxQP4wYd679I5N/tTJOFzbbMmS/Rx/mJV49alwiQRH9A5pxFNRnrrUhee2PDs5ijWwlwal9+e/6uqAu6DDWxVCzlV0rcTct+9m8a3gWcyPeAbxhV3jimY7HrA9XtvbV2udNUr1al5rbW/4O3x++kU8AiAE/VMFF2JD2lGo9KFjKpbceWYOQFQqSq/sdFiinJlfINDV3pnBV2JBUgAfWGD3NzQpbSxkdiI90z7KSeR7HYy7ne0M60ARbscDJBf+k9wMXe7GSVMdaqZTrjaGr8t2y0e5CkZrAthiNevKrKKHK/uosQ1b93F3UK7Npn8j6eLSGCR7DMx8QoLbE0nGyf+bkHULjom0tDfCLOff9TPigT8M62SXNLrl/a3nT4zeljFQdM5C15r/3WEe3a9TL7/1y82Z9rgFVBLjB7NAh83JRej2V5l87j4GX6GrxApL6t2LcXbUFjDDKQVqwqcF3lFo41/X2inf/5Irjlc0VvFILHv0="


# requested env for cross-compilation
env:
  global:
    - TRAVIS_COMPILER: arm-none-eabi-gcc
    - CC: arm-none-eabi-gcc
    - LD: arm-none-eabi-ld
    - CROSS_COMPILE: arm-none-eabi-

script:
  - wget -O gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 "https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2?revision=ca0cbf9c-9de2-491c-ac48-898b5bbc0443&la=en&hash=68760A8AE66026BCF99F05AC017A6A50C6FD832A"
  - tar xf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
  - export PATH=$PWD/gcc-arm-none-eabi-10-2020-q4-major/bin:$PATH
  - make clean
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarScanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output make all
  # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.projectKey=h2lab_leia-solo-firmware -Dsonar.organization=h2lab

notifications:
  email: false
