language: c
os: linux
dist:
    - xenial

addons:
    apt:
        update: true
        packages:
            - make
            - gcc-arm-none-eabi
            - binutils-arm-none-eabi
            - python-pip
            - python3-pip
            - bash

jobs:
    include:
        - stage: buid_matrix
          script:
              - ./build_matrix.sh

notifications:
  email:
    recipients:
      - leia@ssi.gouv.fr
    on_success: never
    on_failure: always
    on_pull_requests: always

