name: leia-firmware

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  vanilla_tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: checkout repository
        uses: actions/checkout@v2
      # Run actions
      # Compilation tests
      - name: compilation tests
        uses: fiam/arm-none-eabi-gcc@v1
        shell: bash
        run: |
          ./build_matrix.sh; 
